---
title: "Inspirations"
date: "2018-01-02T15:07:00"
weight: 100  # Order that this section will appear.
---


* [Structure and Interpretation of Computer Programs][sicp] (and an [interactive version][isicp]) and Lisp (see "[Ancient Text](https://www.technologyreview.com/s/407089/ancient-text/)")
* Smalltalk:
   - Alan Kay
   - [Squeak][squeak], [Squeakland][squeakland], [SqueakJS][squeakjs]
   - [olpc][olpc]
   - [Scratch][scratch]
   - [Croquet][croquet], [OpenQwaq][openqwaq]
   - [Newspeak][newspeak]
* [Virtual World Framework][vwf], [Virtual Worlds][vw]
* Python & Co.
   - [IPython Notebook, now jupyter][ipython]
   - [Collaborative Calculation in the Cloud (was: SageMath on the Cloud!][sagemathcloud]
* [R][r], [RStudio][rstudio], [tidyverse][tv]
* [Inventing fundamental new computing technologies][ifnct]
   - [Fonc][fonc], [Ian's ee380 at Stanford][ian_ee380], [To trap a better mouse][trap]
* [N. Dershowitz](https://www.math.tau.ac.il/~nachumd/), [E. M. Reingold](https://reingold.co/) "[Calendrical Calculations, 3rd Edition][calcal]"
* [Cargo Cult Science][cargocult] ([PDF](https://calteches.library.caltech.edu/51/02/CargoCult.pdf)) 
* [Tufte][tufte]
* [D3.js](https://d3js.org)
* [Kahan][kahan]'s writings, i.e. [Why I can Debug some Numerical Programs You can't][debugnum]
* Botticelli's [Primavera][primavera] (on [Wikipedia][prim_wp]) [the the marvellous book "[Primavera: The Restoration of Botticelli's Masterpiece](https://www.amazon.com/Primavera-Restoration-Botticellis-Umberto-Baldini/dp/0810923149)" by Umberto Baldini, Ornella Casazza] and [Birth of Venus][venus] (on [Wikipedia][venus_wp])
* Van Dyck's [Arnolfini's Marriage][arnolfini]


## Books ##

* (some of) the ones I [read](https://www.goodreads.com/review/list/2866523-enrico?shelf=read)
* the ones I own and would like [to read someday](https://www.goodreads.com/review/list/2866523-enrico?shelf=to-read)

[r]: <https://www.r-project.org/> "R language for Statistical Computing"
[rstudio]: <https://www.rstudio.com/> "RStudio"
[sicp]: <https://mitpress.mit.edu/sicp/full-text/book/book.html> "Structure and Interpretation of Computer Programs"
[isicp]: <https://xuanji.appspot.com/isicp/index.html> "Interactive SICP"
[squeak]: <https://www.squeak.org/> "Squeak"
[squeakland]: <https://www.squeakland.org/> "Squeakland"
[squeakjs]: <https://squeak.js.org/> "SqueakJS"
[ipython]: <https://jupyter.org/> "jupyter"
[sagemathcloud]: <https://cocalc.com/> "SageMath Cloud"
[olpc]: <https://one.laptop.org/> "One Laptop Per Child"
[scratch]: https://scratch.mit.edu/ "Scratch"
[croquet]: <https://en.wikipedia.org/wiki/Croquet_Project> "Croquet"
[openqwaq]: <https://code.google.com/p/openqwaq/> "OpenQwaq"
[newspeak]: <https://newspeaklanguage.org/> "Newspeak"
[ifnct]: <https://vpri.org/html/work/ifnct.htm> "Inventing fundamental new computing technologies"
[fonc]: <https://vpri.org/fonc_wiki/index.php?title=Main_Page> "Fundamental New Computing Technologies"
[ian_ee380]: <https://www.stanford.edu/class/ee380/Abstracts/070214.html> "Ian at Stanford EE Computer Systems Colloquium"
[trap]: <https://www.youtube.com/watch?v=EGeN2IC7N0Q> "To trap a better mouse"
[calcal]: <https://www.cs.tau.ac.il/~nachum/calendar-book/third-edition/> "Calendrical Calculations"
[cargocult]: <https://en.wikipedia.org/wiki/Cargo_cult_science> "Cargo Cult Science"
[tufte]: <https://www.edwardtufte.com/tufte/> "Tufte"
[kahan]: <https://www.cs.berkeley.edu/~wkahan/> "Kahan"
[debugnum]: <https://www.cs.berkeley.edu/~wkahan/Stnfrd50.pdf> "Why I can Debug some Numerical Programs You can't"
[primavera]: <https://notrombone.files.wordpress.com/2007/06/botticelli-primavera.jpg> "Botticelli's Primavera"
[prim_wp]: <https://en.wikipedia.org/wiki/Primavera_%28Botticelli%29> "Primavera"
[venus]: <https://notrombone.files.wordpress.com/2007/06/botticelli_birth_venus.jpg> "Botticelli's Birth of Venus"
[venus_wp]: <https://en.wikipedia.org/wiki/The_Birth_of_Venus_%28Botticelli%29> "Birth of Venus"
[arnolfini]: <https://en.wikipedia.org/wiki/Arnolfini_Portrait> "Van Dyck's Arnolfini's Marriage"
[vwf]: <https://virtual.wf/> "Virtual World Framework"
[vw]: <https://sandbox.adlnet.gov/904/adl/sandbox/> "Virtual Worlds"
[tv]: <https://www.tidyverse.org/> "Tidyverse"
