# Site wide configuration

title:            Home Page
locale:           en_US
url:              http://enrico.spinielli.net


# Jekyll configuration

permalink:   /:categories/:title/
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jemoji

# Site owner
owner:
  name: Enrico Spinielli
  avatar: bio-photo.jpg
  bio: "Maximizing fun...whenever possible!"
  email: enrico.spinielli@gmail.com
  disqus-shortname: enricospinielli
  twitter: espinielli
  facebook: enrico.spinielli
  google:
    plus: EnricoSpinielli
    analytics: UA-56589946-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: espinielli
  gist: espinielli
  stackoverflow: http://stackoverflow.com/users/963575/espin
  linkedin: espinielli
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  blogger: ongiantsshoulders

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
